language: r
dist: bionic


r_packages:
  - rgdal
  - rgeos
  - sp
  - RNetCDF

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libnetcdf-dev
      - libgdal-dev
      - libproj-dev
      - netcdf-bin

cache:
  packages: true

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat "/home/travis/build/earthlab/cft/cft.Rcheck/*check.log"
