language: r
sudo: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -q update
  - sudo apt-get -y install libudunits2-dev

addons:
  apt:
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin
      - libnetcdf-dev
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - python3-venv


before_script:
  - python3 -m pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'cstdata::install_py_deps()'

after_success:
    - Rscript -e 'covr::codecov()'
