language: r
sudo: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  # install libudunits2
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -q update
  - sudo apt-get -y install libudunits2-dev
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - rm miniconda.sh

addons:
  apt:
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev
      - netcdf-bin
      - libnetcdf-dev
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - python3-venv


before_script:
  - python3 -m pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e "cstdata::install_py_deps(method='conda')"

after_success:
    - Rscript -e 'covr::codecov()'
